### Numpy stand for Numerical Python. It is very fast and efficient compare to normal python list
### All the element in the numpy array should be Homogeneous.
### It is mostly used for Integer/Float data type, you can also use String data type
### Let's see practical example now.

In [3]:
import numpy as np # Importing numpy and giving the alias as np

In [3]:
X = np.array([[1,2,4],[4,5,6],[5,4,3]]) # Providing the element in the array 

In [4]:
print(X)
print(X.shape) # It will tell us the how many rows and column have like ( row, column)
print(X.dtype) # refer to data type - Int, string, float, bool 
print(X.ndim) # number of dimension like 1d, 2d, 3d.......nd
print(X.size) # total number of element in the array same as python len method
print(type(X)) # what type of object is it like numpy.ndarray or list etc


[[1 2 4]
 [4 5 6]
 [5 4 3]]
(3, 3)
int32
2
9
<class 'numpy.ndarray'>


In [5]:
lst = [1,2,4]
Y = np.array(lst)
print(Y)

[1 2 4]


In [6]:
Z = np.array([1,2,4,'Hello',3.4]) # Here I am providing int,str and float element but when I see the data type
print(Z)
print(Z.dtype)# All changed to string because of one string element

['1' '2' '4' 'Hello' '3.4']
<U32


In [7]:
Z = np.array([1,2,4,3.4]) # Here I am providing int,str and float element but when I see the data type
print(Z)
print(Z.dtype)# All changed to float because of one float element

[1.  2.  4.  3.4]
float64


In [8]:
## So priority is : String > Float > Integer

In [9]:
Z = np.array([1,2,4,'Hello',3.4,False]) # Here I am providing int,str and float element but when I see the data type
print(Z)
print(Z.dtype)# All changed to string because of one string element

['1' '2' '4' 'Hello' '3.4' 'False']
<U32


In [10]:
A = np.array([[1,2,4],[5,4,3,5]])
# It will raise an error because all the element should be same size either 3 or 4 in the example because it is
#unambiguous while determining the A.shape(row, col) here row is 3 but col is (3,4) that why it will give an error
print(A)

[list([1, 2, 4]) list([5, 4, 3, 5])]


<ipython-input-10-8e74ac0d56ac>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  A = np.array([[1,2,4],[5,4,3,5]])


## using built in function
### zeros,ones,eye,diag,full,arange,linspace,reshpae,random

In [17]:
X = np.zeros((6,4)) # it is used for creating a empty or zeror array ((x,y,z.....n)) number of dimension
print(X)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
X = np.ones((4,3)) # it is used for creating a array with all 1 ((x,y,z.....n)) number of dimension
print(X)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
X = np.full((4,3),6)# used for creating constant value of array
print(X)

[[6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]]


In [23]:
X = np.eye(6)# set the one for the diagonal
print(X)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [26]:
X = np.arange(5,10)# it like a range function in list ( start, end, step) - ( included start, excluded end)
print(X)

[5 6 7 8 9]


In [27]:
X = np.linspace(3,4,20)# it is evenly distriubted the value in step ( start, end, step) ( included start and end)
print(X)

[3.         3.05263158 3.10526316 3.15789474 3.21052632 3.26315789
 3.31578947 3.36842105 3.42105263 3.47368421 3.52631579 3.57894737
 3.63157895 3.68421053 3.73684211 3.78947368 3.84210526 3.89473684
 3.94736842 4.        ]


In [28]:
X = np.linspace(3,4,20,endpoint=False)# same as above but included start and excluded end
print(X)

[3.   3.05 3.1  3.15 3.2  3.25 3.3  3.35 3.4  3.45 3.5  3.55 3.6  3.65
 3.7  3.75 3.8  3.85 3.9  3.95]


In [29]:
X = np.reshape(X,(5,4))# used for giving the new shape of array like giving the number of dimensional
# but if array is by deafault one dimensional and you can make it multidimensional using reshpae method
# point to be noted : if array has 20 element then multiplication of reshape should be 20 like (4,5)=20 , (10,2)=20
#otherwise it will raise an error if you specify like (3,10)=30 which is false
print(X)

[[3.   3.05 3.1  3.15]
 [3.2  3.25 3.3  3.35]
 [3.4  3.45 3.5  3.55]
 [3.6  3.65 3.7  3.75]
 [3.8  3.85 3.9  3.95]]


In [34]:
X = np.reshape(X,(5,3))

ValueError: cannot reshape array of size 20 into shape (5,3)

In [35]:
X = np.arange(10).reshape((5,2))#you can use reshape like this you do not have to pass array

print(X)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [39]:
X = np.linspace(4,5,6).reshape((3,2)) # reshpae(6), reshape((3,2)) both are true
print(X)

[[4.  4.2]
 [4.4 4.6]
 [4.8 5. ]]


In [41]:
X = np.random.random(10)
print(X)

[0.54588734 0.75829418 0.11557354 0.52223522 0.64979764 0.84771917
 0.00976786 0.3978441  0.88593537 0.17290891]


In [49]:
X = np.random.randint(3,10,size=(3,7))
#NumPy also allows us to create ndarrays with random integers within a particular interval.
#The function np.random.randint(start, stop, size = shape) creates an ndarray of the given shape 
#with random integers in the half-open interval [start, stop).
print(X)

[[5 9 7 7 5 8 4]
 [8 8 9 3 6 7 4]
 [5 7 7 9 6 4 9]]


In [53]:
X = np.random.normal(0,0.1,size=(1000,1000))# np.random.normal(mean, standard deviation, size=shape)
print(X)
print(X.mean())
print(X.std())

[[-0.0754874   0.00955045 -0.08491673 ... -0.03087646 -0.05333109
  -0.09651706]
 [-0.13516238  0.13407862 -0.04540702 ...  0.15391053 -0.04417964
  -0.16508774]
 [-0.09197113 -0.17274168 -0.10611965 ... -0.22056281  0.10313987
  -0.02563527]
 ...
 [-0.06364464 -0.10089427  0.08351702 ... -0.03753913  0.05099814
   0.03572922]
 [-0.00520985 -0.10803878  0.0441431  ... -0.05635035  0.37380042
   0.08859737]
 [ 0.07389125  0.03601875  0.05302981 ... -0.05530995 -0.05440823
   0.0398181 ]]
7.638838452057584e-05
0.10004871345260692


### indexing, adding,deleting, inserting, hstack, vtack

In [54]:
x = np.array([1,2,3,4,5])
print(x[3])

4


In [67]:
x = np.array([[1,2,4],[6,54,6]])
print(x[1,2])
print(x)

6
[[ 1  2  4]
 [ 6 54  6]]


In [64]:
y = np.append(x,[[4,3,2]],axis=0)#(array,what to add, which axis)
print(y)

[[ 1  2  4]
 [ 6 54  6]
 [ 4  3  2]]


In [69]:
z = np.append(x,[[4],[3]],axis=1)#(array,what to add, which axis)
print(z)

[[ 1  2  4  4]
 [ 6 54  6  3]]


In [70]:
z[0,3]=44

In [71]:
z

array([[ 1,  2,  4, 44],
       [ 6, 54,  6,  3]])

In [72]:
z[0]=5

In [73]:
z

array([[ 5,  5,  5,  5],
       [ 6, 54,  6,  3]])

In [74]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [75]:
y = np.delete(x,[0],axis=0)#(ndarray,what to delete, which axis)
print(y)

[[4 5 6]
 [7 8 9]]


In [76]:
y = np.delete(x,[1],axis=1)#(ndarray,what to delete, which axis)
print(y)

[[1 3]
 [4 6]
 [7 9]]


In [77]:
y = np.insert(x,1,[[4,4,4]],axis=0)#(ndarray, where to insert, what to insert, axis row or column)
print(y)

[[1 2 3]
 [4 4 4]
 [4 5 6]
 [7 8 9]]


In [79]:
y = np.insert(x,2,[[4,4,4]],axis=1)#(ndarray, where to insert, what to insert, axis row or column)
print(y)

[[1 2 4 3]
 [4 5 4 6]
 [7 8 4 9]]


In [80]:
a = np.array([1,2])
b = np.array([[3,4],[5,6]])
vstack = np.vstack((a,b))
print(hstack)

[[1 2]
 [3 4]
 [5 6]]


In [88]:
hstack = np.hstack((b,a.reshape(2,1)))
print(vstack)

[[3 4 1]
 [5 6 2]]


## Slicing

In [1]:
# array[start:end] , included start element and excluded end element
# array[start:] , start and till the end of the array
# array[:end], it will grab all the element from the begining till the end-1 indices


In [6]:
X = np.arange(1,21).reshape(5,4)
print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [8]:
z = X[1:4,1:] # start from row 1 to 3, and start from column 1 to till the end of the array column
print(z)

[[ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [12]:
y = X[2:,3]# it will give the all the element starting from row 2 and column 3 but it is giving rank 1 array
print(y)

[12 16 20]


In [13]:
y = X[2:,3:]# it will give the all the element starting from row 2 and column 3 , to getting the rank 2 include : or indices
print(y)

[[12]
 [16]
 [20]]


In [14]:
z[2,2]=666# if you change the any element in this array then it will also reflect to the original array X
print(z)
print(X)

[[  6   7   8]
 [ 10  11  12]
 [ 14  15 666]]
[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [ 13  14  15 666]
 [ 17  18  19  20]]


In [15]:
#you can see that 666 is also reflect in the original array

In [18]:
z = X[2:,1:].copy()# using the copy method it will not relfect the original array you can alos use np.copy(array,[slicing])
print(z)

[[ 10  11  12]
 [ 14  15 666]
 [ 18  19  20]]


In [19]:
z[0,0]=1111
print(z)
print(X)

[[1111   11   12]
 [  14   15  666]
 [  18   19   20]]
[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [ 13  14  15 666]
 [ 17  18  19  20]]


In [20]:
A = np.diag(X)# finding the diagonal element
print(A)

[  1   6  11 666]


In [27]:
A = np.diag(X,k=1)#k from where you want to start the diagonal element by default k=0
print(A)

[ 2  7 12]


In [30]:
#finding the unique  element in the array
arr = np.random.randint(1,10,size=(4,5))
print(arr)
unique = np.unique(arr)
print("UNIQue\n",unique)

[[7 4 8 4 6]
 [9 4 6 3 3]
 [6 4 1 4 5]
 [3 9 4 8 4]]
UNIQue
 [1 3 4 5 6 7 8 9]


## Boolean indexing, set operation , sorting

In [31]:
X = np.arange(25).reshape(5,5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [32]:
X>10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [34]:
X[(X>10)]#returing all the element which is greater than 10


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
greater10_less19 = X[(X>10) & (X<19)]#greater than 10 and less than 19
print(greater10_less19eater10_less19)

[11 12 13 14 15 16 17 18]


In [39]:
X[(X>5)&(X<8)]=-1#if this condition met then it will change the value 
print(X)

[[ 0  1  2  3  4]
 [ 5 -1 -1  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [40]:
X = np.random.randint(1,15,size=(5,5))
print(X)

[[ 1  6 12  3 12]
 [ 3 10  6  9  3]
 [ 6  6 12  6  7]
 [ 3  8  8 13 12]
 [ 2 11  7  9  5]]


In [41]:
#using np.sort method it will not sort in place using the sort method it will sort the element in place
print(np.sort(X,axis=0))
print(X)

[[ 1  6  6  3  3]
 [ 2  6  7  6  5]
 [ 3  8  8  9  7]
 [ 3 10 12  9 12]
 [ 6 11 12 13 12]]
[[ 1  6 12  3 12]
 [ 3 10  6  9  3]
 [ 6  6 12  6  7]
 [ 3  8  8 13 12]
 [ 2 11  7  9  5]]


In [42]:
#using np.sort method it will not sort in place using the sort method it will sort the element in place
print(np.sort(X,axis=1))
print(X)

[[ 1  3  6 12 12]
 [ 3  3  6  9 10]
 [ 6  6  6  7 12]
 [ 3  8  8 12 13]
 [ 2  5  7  9 11]]
[[ 1  6 12  3 12]
 [ 3 10  6  9  3]
 [ 6  6 12  6  7]
 [ 3  8  8 13 12]
 [ 2 11  7  9  5]]


In [43]:
X.sort(axis =0)# it sort the value in place
print(X)

[[ 1  6  6  3  3]
 [ 2  6  7  6  5]
 [ 3  8  8  9  7]
 [ 3 10 12  9 12]
 [ 6 11 12 13 12]]


In [48]:
A = np.array([2,3,4,5,6])
B = np.array([1,2,6,7,8])
print(np.intersect1d(A,B))#common element in both the array
print(np.setdiff1d(A,B))#element which is present in A but not in B
print(np.setdiff1d(B,A))#element which is present in B but not in A
print(np.union1d(A,B))#combine the distinct element in A and B


[2 6]
[3 4 5]
[1 7 8]
[1 2 3 4 5 6 7 8]


## Arithmetic operation and broadcasting

In [49]:
x = np.array([1,2,4])
y = np.array([6,7,8])

In [51]:
#addition
print(x+y)
print(np.add(x,y))#both are equivalent

[ 7  9 12]
[ 7  9 12]


In [52]:
#subtraction
print(x-y)
print(np.subtract(x,y))#both are equivalent

[-5 -5 -4]
[-5 -5 -4]


In [53]:
#multiplication
print(x*y)
print(np.multiply(x,y))#both are equivalent

[ 6 14 32]
[ 6 14 32]


In [54]:
#divide
print(x/y)
print(np.divide(x,y))#both are equivalent

[0.16666667 0.28571429 0.5       ]
[0.16666667 0.28571429 0.5       ]


In [57]:
#modulo - remainder
print(x%y)
print(np.remainder(x,y))#both are equivalent

[1 2 4]
[1 2 4]


In [58]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [59]:
a+b

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [60]:
a-b

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [63]:
print(a%b)
print(b%a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 1]
 [2 0 4]
 [3 2 1]]


In [67]:
r = np.array([1,2,3,4])
print(np.sqrt(r))
print(np.exp(r))
print(np.power(r,2))

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 1  4  9 16]


In [68]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))


X = 
 [[1 2]
 [3 4]]

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]


In [69]:
x = np.arange(1,10).reshape(3,3)
y = np.array([9,8,7])

In [70]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
y

array([9, 8, 7])

In [72]:
x+y

array([[10, 10, 10],
       [13, 13, 13],
       [16, 16, 16]])

In [74]:
z = np.array([8,7,6]).reshape(3,1)
z

array([[8],
       [7],
       [6]])

In [75]:
x+z

array([[ 9, 10, 11],
       [11, 12, 13],
       [13, 14, 15]])

In [76]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('3 * X = \n', 3 * X)
print()
print('3 + X = \n', 3 + X)
print()
print('X - 3 = \n', X - 3)
print()
print('X / 3 = \n', X / 3)


X = 
 [[1 2]
 [3 4]]

3 * X = 
 [[ 3  6]
 [ 9 12]]

3 + X = 
 [[4 5]
 [6 7]]

X - 3 = 
 [[-2 -1]
 [ 0  1]]

X / 3 = 
 [[0.33333333 0.66666667]
 [1.         1.33333333]]
